export const PATHS = {
  root: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  employees: "/employees",
  reports: "/reports",
  candidates: "/candidates",
  error: "/page-not-found",
  hrDashboard: "/dashobard/hr-dashboard",
  devDashbnoard: "/dashboard/dev-dashboard",
  adminDashboard: "/dashboard/admin-dashboard",
  adminErrorPage: "/dashboard/error-admin-dashboard",
  hrErrorPage: "/dashboard/error-hr-dashboard",
  devErrorPage: "/dashboard/error-dev-dashboard",
  employeesDashboard: "/dashboard/employee-dashboard",
  candidateDashbnoard: "/dashboard/candidate-dashboard",
  superAdminPage: "/super-admin-dashboard",
};
